### ISSUE TITLE
[bug] Gearswap equip gear in order not working for some variables

### ISSUE THREAD

**Issue by sebyg666** [Windower/Lua#1069]
this is refering to gearswaps ability to create an order in which peices of gear get equiped. 
Moreover this is specifically regarding passing a variable as the name.

for example
main = gear.FastcastStaff
main={ name = gear.Staff.PDT, order = 1} 
the above 2 both work, i checked using the //gs showswaps command

however this
main={ name = gear.FastcastStaff, order = 1)

does not work at all even though im using the exact same variable as above. Gearswap throws a error
line 59 of equip processing "attempt to call method "lower" (a nil value).

just thaugh id mention this, it should be easily replicated. I realise the above uses motentons variables from his files but it still doesnt make sence to me that one would work and the other with the order defined, not. 

one thing to note, gear.staff.pdt refers to only 1 staff while fastcast refers to a table of staffs. this could be the issue, but again why does (main = gear.FastcastStaff) work but not the other with the order defined.
Anyway ill leave it to you guys to figure it out lol. thanks in advance.

**Comment by Byrth** [comment]
It is likely lower being called on a table value, which lower is not defined for. I will check this out tonight.

Ftr, my tracker is: https://github.com/Byrth/Lua/issues

**Comment by Byrth** [comment]
After looking at his code, gear.FastcastStaff is a table that contains the name element already. So the examples are:

works:
main={name="words", etc.}
main={name=gear.Staff.PDT,order=1}

doesn't work:
main={name={name="words",etc.},order=1}

To fix the bug, I will add a check that ensures names are strings. Now it will simply not work instead of causing an error.

Also, the order option was removed in favor of priority, which I apparently forgot to document and actually don't remember how it works. I'll try to add that tonight.
