### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by StevenTylerTSO** [Windower/Lua#1126]
Upon reading the repository for this addon, I realized I have no data folder in my Rhombus folder, and thus none of the files it should contain. When I log in to the game, the addon loads and it shows me the green menu (on the rightmost bottom corner of my screen, overlapping my in-game generated stats) with some spells set on it. I can't move it or do anything other than target and attempt casting spells. I tried to explain the situation as best as I could, but I'm aware I might be missing something and the addon working as it should and it might be just that I'm not understanding it. Either way, I hope you can shed some light as to what I need to do to make it work or fix whatever bug it has, if any. Anticipated thanks.

**Comment by z16** [comment]
I'm not sure there's a problem... I don't think it can be moved (it's supposed to cover SE's display, it's supposed to replace it, not amend it). What else did you want to adjust? Is something not working as it should?

**Comment by StevenTylerTSO** [comment]
Whether I am a DRG/DNC or a THF/WHM, I only get the magic menu; right clicking doesn't cycle menus. And I don't have that data folder in my Rhombus folder. All there is in there are defs.lua, ReadMe.md, and Rhombus.lua.

**Comment by StevenTylerTSO** [comment]
Also, the usage section of the repository says the menu can be repositioned by holding down shift and clicking anywhere within the icon. I can't do that either.

**Comment by z16** [comment]
First of, my bad for mixing up Rhombus and Nostrum, I've never used Rhombus (or seen it in use), so I cannot comment on where it should be. Second, the data folder will not be created unless the addon specifies it (it has (almost) no special meaning for Windower), so you'll have to create that yourself. I cannot make further comments on it, but I'll notify the addon's author of this issue.

**Comment by StevenTylerTSO** [comment]
Thank you very much. :)

**Comment by StevenTylerTSO** [comment]
I think I'm beggining to figure it out. I see what you mean I have to create the folder and files.

**Comment by trv6** [comment]
Are you confusing Nostrum with Rhombus? For reference: https://www.dropbox.com/s/wo2aeo999qw6sb8/rhovnos.png?dl=0

Both will create data folders after the first time they are loaded, but Nostrum will create a default file while Rhombus will not.

Nostrum is not draggable, but can be repositioned in the settings file. Rhombus is draggable by holding shift and then left-clicking.

**Comment by StevenTylerTSO** [comment]
Yes, I was confusing them. Right now I've been trying to figure out Yush instead. I'm  trying to write a small macro to test it out but when I change back to the corresponding job, Windower tells me there is no file for that JOB/SUB.

This is what I got so far:

WHM = {
    [Ctrl+1] = "input /ma cure <st>",
    [Ctrl+2] = "input /ma protectra <me>",
}

JA = {
    [Alt+1] = "input /ja range <stnpc>",
}
end

**Comment by trv6** [comment]
Did you try skimming through the ReadMe:https://github.com/Windower/Lua/blob/4.1-dev/addons/Yush/ReadMe.md?

Put quotes around the keys in your table (['Ctrl+1']=...), and return a table at some point.

WHM = {
    ['Ctrl+1'] = "input /ma cure ",
    ['Ctrl+2'] = "input /ma protectra ",
}
JA = {
    ['Alt+1'] = "input /ja range ",
}

return{
    ['Ctrl+1']=WHM,
    ['Ctrl+2']=JA,
}

Place that in a file and name it character_name_WHM.lua

That would create a macro set where hitting Ctrl 1 took you to the WHM table. Pressing Ctrl 1 again would input cure. Returning to the base layer (by pressing ~, unless you've set it to use a different key) and pressing Ctrl 2 would access the JA table. Pressing Alt 2 would then input /ja range (is that a job ability?).

**Comment by StevenTylerTSO** [comment]
No, it's not... hehe... so I changed it. Here's what my THF_WHM file looks like now:

```
['Alt+1'] = 'input /range <stnpc>',
```

WHM = {
    ['Ctrl+1'] = 'input /ma "cure" <st>',
    ['Ctrl+2'] = 'input /ma "protectra" <me>',
}

DJA =
    ['Ctrl+1'] = 'input /ja "Sneak Attack" <me>',  
    ['Ctrl+0'] = 'input /ja "Perfect Dodge" <me>',
}

WS = {
    ['Alt+1'] = 'input /ws "Gust Slash" <bt>',
}

OJA = {
    ['Alt+1'] = 'input /ja "Steal" <bt>',
}

return {
    ['Ctrl+1'] = WHM,
    ['Ctrl+2'] = DJA,  
    ['Alt+1'] = WS,
    ['Alt+3'] = OJA,
}
end

I also made these:

Dragolas_THF.lua:

WHM = {
    ['Ctrl+1'] = 'input /ma "cure" <st>',
    ['Ctrl+2'] = 'input /ma "protectra" <me>',
}

DJA = {
    ['Ctrl+1'] = 'input /ja "Sneak Attack" <me>',  
    ['Ctrl+0'] = 'input /ja "Perfect Dodge" <me>',
}

WS = {
    ['Alt+1'] = 'input /ws "Gust Slash" <bt>',
}

OJA = {
    ['Alt+1'] = 'input /ja "Steal" <bt>',
}

return {
    ['Ctrl+1'] = WHM,
    ['Ctrl+2'] = DJA,
    ['Alt+1'] = 'input /range <stnpc>',
    ['Alt+2'] = WS,
    ['Alt+3'] = OJA,
}

local sub = windower.ffxi.get_Dragolas.sub_job
if sub == 'WHM' then
    include('WHM-include.lua')
elseif sub == 'WAR' then
    include('WAR-include.lua')
end

WHM-include.lua:

WHM = {
    ['Ctrl+1'] = 'input /ma "cure" <st>',
    ['Ctrl+2'] = 'input /ma "protectra" <me>',
}

Of course they're still works in progress. It still gives me the "Yush: No matching file found for Dragolas (THF/WHM)."

**Comment by Antinym** [comment]
--- edit --- oops, it should load the macro sets as; name_main_sub.lua, name_main.lua, name.lua.  Certain errors in the macro file, missing comma in a table for one,  Yush will only report  'no file found.'

**Comment by z16** [comment]
Another error is this:

``` lua
local sub = windower.ffxi.get_Dragolas.sub_job
```

It should instead be:

``` lua
local sub = windower.ffxi.get_player().sub_job
```

Also, it would be easier if you posted the files elsewhere (like [here](https://gist.github.com/)), so they're easier to format and read.

**Comment by StevenTylerTSO** [comment]
Ok, I made a few corrections and added the Dragolas.lua file. I'm understanding the language better now, I think. Windower still gives me the same message. I'm wondering about this binds.lua file mentioned in the readme.md file. Anyways, I'm ready to post the files at Gists but I'm wondering, should I make the gist public or can you read it regardless?

**Comment by joshk6656** [comment]
If you do secret gists, anyone with the URL can read them.

**Comment by StevenTylerTSO** [comment]
Oh, OK, so I'll just make it public. It's not like it has sensitive info. Thanks.

**Comment by StevenTylerTSO** [comment]
Here's the URL:

https://gist.github.com/54da2aed3cf3ec6c27d0

**Comment by z16** [comment]
What Josh said was that we _can_ see it even if it's secret. The difference is that public gists are listed, so people can find it without a link. Secret gists can still be shared fine with a link.

About the files, there are a few errors in there. Most files have an `end` token at the end, which should be removed. Only blocks need to be closed with an `end` keyword (i.e. `if`, `for`, `function` and `while` sections). Having an `end` at the end of the file that isn't closing any block will count as an error.

Second, in the `Dragolas_THF.lua` file, the return statement should be after the `if` block. Anything after a return statement is ignored, so that will never be called.

Third, you're re-using a lot of code that could be put into includes. For example, in your `Dragolas_THF.lua` you can add `include('Dragos.lua')` at the top, then you can remove everything in `Dragolas_THF.lua` that is in the included file (for example all the map and FFXIDB related key bindings).

**Comment by StevenTylerTSO** [comment]
First, thank you all for all the help. That being said, yes, I understood what Josh said; but then it made me realize that by making it secret it would still be exposed, (which I try to be careful what I share on the internet) but by making it public, people having this same issue would be able to find it even if they didn't come across this thread and it might help them. I just made a note in the description to warn that **the files are still being tested** and also added a link to this thread.

One other question, do I need to enumerate the entries and format them to 2 and 4 spaces respectively?

**Comment by z16** [comment]
No and no. But just fyi, you can remove `Dragolas_THF_WHM.lua` and it would still work the same as now, the file is currently redundant.

However, coming back to the original issue, is that problem solved for you now or do you still need help with something? If not, I'd like to close this issue. For support questions you should ask on the forums or on IRC, it's easier to talk there since it usually requires a bit of dialogue. Also, it keeps this tracker reserved for actual bugs.

**Comment by StevenTylerTSO** [comment]
I'll see if it works and get back to you.

**Comment by StevenTylerTSO** [comment]
Gonna have to revise, still giving me the same dialog.

**Comment by z16** [comment]
Can you be more specific please? It will make debugging easier.

**Comment by StevenTylerTSO** [comment]
Oh, sorry, I was just working on it myself. I implemented all your suggestions and Yush still tells me "no matching file found for Dragolas (THF/WHM) i just found an error where I had typed `}` instead of `].`. about to change jobs now to see if that fixed it.

**Comment by StevenTylerTSO** [comment]
Yep, that did it. I'm getting "Loaded Dragolas file" now. Still, nothing happens when I press key combinations like `['Ctrl+0']`, which is supposed to return a table. But still, I suppose there's an error in `Dragolas_THF.lua`, since it should take priority over `Dragolas.lua`.

**Comment by z16** [comment]
Ok, two more things, first it should read `include('Dragolas.lua')` (with the single quote) and second you don't need the `input` in `Dragolas.lua` when it's followed by `//`, that's the same as emitting it altogether:

``` lua
FFXIDB = {
    ['Ctrl+1'] = 'ffxidb m z-',
    ['Ctrl+2'] = 'ffxidb m z+',
}
```

In fact, you could shorten a lot more of it if you used the _Shortcuts_ addon. But the latter should at least not be an error. As for why it doesn't work, I'm not sure, I can't spot any obvious errors. In this case it's best to go back to basic, trim the file of everything but a simple statement:

``` lua
return { ['Ctrl+1'] = 'input /echo hello' }
```

Then see if that works. If no, let me know, because the error must be in _Yush_ then. If it does work, start adding more and more stuff until you approach the previous file. At some point it should stop working and then you know when the error appears.

Either way, I'm closing this issue as it's not at all related to the original post (or title) anymore and the thread has been completely derailed. If you still have issues with _Yush_, please post on the forums or let us know on IRC, unless you suspect it's an actual bug, in which case feel free to open another issue.
