### ISSUE TITLE
treasury additions

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1137]
i added a check for invitory about every 30 seconds if autodrop is enabled to find any items that might have been missed

i also added a forcecheck using command //tr forcecheck to force treasury to check invitory and drop any item you do not want

i tried to do this through github but every time i try to make a request it put it here https://github.com/Windower/Lua/pull/1128 and for the life of me i cant find out why

but here is the file
http://pastebin.com/gUdXsZ7w

**Comment by z16** [comment]
When you submit a pull request you submit your entire branch, and not just a certain commit of yours. Every other change you make in that branch will automatically be included in the same pull request. To submit this you can create a new branch.

That said, I don't think those features should be added as they rely on Treasury being broken. If Treasury is working right, neither the force check command nor the timed force check should ever find something, since nothing should be missed. If something was missed it's a bug and Treasury should be fixed for it, but instead this would mask the bug. As such I don't think those should be added, but I'm open for arguments to the contrary.

Either way, closing this issue, if you want to submit this as a pull request create a new branch (from the original fork, not your adjusted fork) and submit a new pull request for that.

**Comment by smd111** [comment]
the problem is if 2+ of the same item drops treasury will sometimes only drop 1 of them

**Comment by z16** [comment]
Ok, that's a bug in Treasury then and should be fixed properly.

**Comment by smd111** [comment]
the thing is it only happens when you go from battle to battle realy fast or if you kill mob after mob with in a few seconds some of the items get missed

and this causes items to get put in to your inventory and never removed unless you reload treasury
