### ISSUE TITLE
[Gearswap](live) item use not trigering functions precast or aftercast

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1237]
not sure if it should any more but gearswap is not triggering on item use

**Comment by Byrth** [comment]
Are you using it from the command line or menu?

**Comment by smd111** [comment]
menu

**Comment by Byrth** [comment]
GearSwap has never worked for precast or aftercast on items from the menu.

Items from the menu do not pass through the outgoing text buffer. GearSwap would require an entirely separate system of packet interception and injection to deal with them, which would add ~half a second to the use time. If someone is using items from the menu, they want it to be fast (generally spamming holy waters or something), so that seems like a bad plan.

Anyway, not a bug and no plans to add it.

**Comment by smd111** [comment]
ok that's understandable
