### ISSUE TITLE
[Request] Implement <t> into Send plugin.

### ISSUE THREAD

**Issue by evan64** [Windower/Lua#1299]
I was sent this way from Iryoku. I am requesting this function.

> `//send @all /pet "Assault" <t>`
> However `<t>` is not handled by the Send addon, because at the time it was written our API didn't expose target information to addons. If you open an issue for this on our issue tracker, it would be quite trivial to add support for `<t>`

**Comment by Byrth** [comment]
What is currently unhandled?

I see two options:
1) You want every account to simultaneously use that command. - I'm pretty sure this is already what it does.
2) You want every account to simultaneously use that command on the monster you are targeting, - This is actually not trivial and would require parsing command attempts both when sending and receiving them.

Given that I'm pretty sure it already does the first case and the second case would require the implementation of a function that changes targets for the player, I'm going to close this issue. Feel free to reopen it if the issue was actually the first one and it doesn't work for some reason.

**Comment by z16** [comment]
For the record, the second already has its own issue report and I'll work on that soon.

**Comment by evan64** [comment]
Oh, okay. I'll stick with ashita until this gets fixed. I prefer windower but i need that functionality to play the way I do. thank you for your time.

edit: to clarify the issue for was for option number 2, byrth.
