### ISSUE TITLE
(Request)[gearswap] delayed equip

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1321]
Please add a way to do a delayed equip like this

```
equip:prepare(<setname>):schedule(<delaytimeinseconds>)
```

because currently the only way to do a delayed equip is by forcing an equip_command to run by

```
send_command(wait <delaytimeinseconds>;gs equip <setname>)
```

or

```
gearswap.equip_sets:prepare('equip_command',nil,<setname>):schedule(<delaytimeinseconds>)
```

i have even tried this but it does not work it just ignores that i requested my gear to change

```
function equip_delay(set)
    equip(set)
end
equip_delay:prepare(<setname>):schedule(<delaytimeinseconds>)
```

**Comment by z16** [comment]
The `equip` function does not actually equip anything, so it's not surprising that the latter won't work. This might be much more complex than it seems, because a lot of things are done based on precise timing and sequencing. But just for the record, this is a bit shorter and should also work:

``` lua
gearswap.equip_sets:schedule(<delay>, 'equip_command', nil, <set>)
```

That way you don't need the prepare function. The prepare function is only good if you want to create a new function with the arguments already defined, like:

``` lua
local fn = gearswap.equip_sets:prepare('equip_command', nil, <set>)
fn:schedule(<delay>)
```

That way you can store the function with the arguments, then just call it another time. But this way you can't change the set anymore. Another way to do this, which would let you adjust the set would be this:

``` lua
local fn = gearswap.equip_sets:apply('equip_command', nil)
fn:schedule(<delay>, <set>)
```

**Comment by smd111** [comment]
i did not know you could call a function and pass any unused variables to a :ed function thats good to know

well i decided to do this then

```
c_equip = gearswap.equip_sets:apply('equip_command', nil)
c_equip:schedule(<delay>, <set>)
```

but it would be nice if i could do something like this but not sure if its even possible

```
c_equip = gearswap.equip_sets:apply('equip_command', nil):schedule()
c_equip(<delay>, <set>)
```

**Comment by z16** [comment]
It is, just not with this shortcut syntax. You have to define the function like this:

``` lua
c_equip = function(delay, set)
    return gearswap.equip:schedule(delay, 'equip_command', nil, set)
end

c_equip(<delay>, <set>)
```

**Comment by Byrth** [comment]
Any attempt to use coroutine.sleep from within the GearSwap user environment causes a C error that I'm unable to fix, so the only option is loop back through GearSwap.

Thus, I'm going to close this request because it can already be accomplished using send_command and looping back through GearSwap and there is no better way to do it until LuaCore changes.
