### ISSUE TITLE
Suggestion: Findall addon - Quests current/complete search.

### ISSUE THREAD

**Issue by Pheelix** [Windower/Lua#1550]
Any chance on being able to add a findall search for quests that you might have/done?

**Comment by alphaONE2** [comment]
Quests are a bit harder to do, since we don't currently have quest resources, and quest status isn't in our API. It can certainly be done, but we don't have any plans to add this to the addon ourselves.

If you wanted to try and do this yourself, or find someone willing to do it for you, the following would need to be done to get this to work:
1. [ResourceExtractor](https://github.com/Windower/ResourceExtractor) would need to be updated to extract quest names.
2. Quest data packets would need to be analyzed and added to [fields.lua](https://github.com/Windower/Lua/blob/dev/addons/libs/packets/fields.lua).
3. Quest data would need to be tracked and persisted by the addon so that it can be searched.

**Comment by z16** [comment]
Fwiw, I plan to add it to ResourceExtractor myself soon, I opened [this issue](ResourceExtractor/#48) for it.

**Comment by Byrth** [comment]
People got annoyed when I added KIs, so I'm hesitant to add any more features to findAll.

**Comment by Pheelix** [comment]
annoyed huh? I find it quite useful.  Cuts down the time for tracking KI's down in your list.  Maybe a Quest find addon by its self would be better then adding it to findall.   As i am not good enough to make such a addon I will leave it be.
