### ISSUE TITLE
(bug) windower.text.get_extents()

### ISSUE THREAD

**Issue by sebyg666** [Windower/Lua#1648]
```lua
windower.text.create('foo')
windower.text.set_text('foo', 'Testing')
windower.text.set_font('foo', 'Arial')
windower.text.set_font_size('foo', 14)
print(windower.text.get_extents('foo')) --> 0, 0
```
i could really do with getting the extents for my text boxes. please help. thanks
edit -- DEV version

**Comment by smd111** [comment]
windower.text.get_extents(name) only return the location of it and sense you never specified any ofcorse its 0,0

**Comment by trv6** [comment]
Nah, `get_extents` returns the dimensions of the text object. However, the text has to be rendered first.

I'm not sure if there's a graceful way to get the dimensions. Set the text in `prerender`, then measure it in `postrender`? Still, the text needs to be rendered and `visible` for one frame before any changes you make will take effect. If it's a simple scenario, delaying the function with `coroutine.schedule` provides a quick & dirty solution.

You can sidestep the problem with monospaced fonts, occasionally rendering text offscreen, and writing dimensions to disk for later use. Problems like determining how much text should be displayed within a text field so that it does not continue beyond the boundaries are probably best left to Windower 5.

**Comment by smd111** [comment]
@trv6 
yes your correct i messed up windower.text.get_extents gives you the x,y pixel length so if you have nothing displayed it will always be 0,0

here are some good things to have in your back pocket just encase you need them
PixelLengthX, PixelLengthY = texts.extents(_G['foo'])
LinesCount = _G['foo']:text():count('\n') + 1
LineOffset = PixelLengthY / LinesCount
--below this is only useful if you are using prim's
this gives you the the y dimensions of ever line in your display based on the line you are looking at (based from the x,y locations of the _G['foo'].pos.x/_G['foo'].pos.y of your display)
local location = {}
location[1] = {}
--gives the start y of the selected line
location[1].ya = 1
--gives the end y of the selected line
location[1].yb = LineOffset
local count = 2
while count <= LinesCount do
    location[count] = {}
    location[count].ya = location[count - 1].yb
    location[count].yb = location[count - 1].yb + LineOffset
    count = count + 1
end

check these if you want to see more of my display code (this will be hard to understand)
https://github.com/smd111/Gearswap/blob/master/SMDinclude/includes/more/Display.lua
https://github.com/smd111/Gearswap/blob/master/SMDinclude/includes/more/Display_sub.lua

**Comment by trv6** [comment]
Oh, whoops. Duplicate error. [994](https://github.com/Windower/Issues/issues/994)

**Comment by sebyg666** [comment]
yeah sorry, i realised i posted the issue in the wrong thread, as this is a core windower function and not lua related. either way thank you for the replies.
