### ISSUE TITLE
Treasury multibox issue.

### ISSUE THREAD

**Issue by OverloadingTrucks** [Windower/Lua#1908]
The settings.xml is getting all wonky when multiboxing. I've had to erase and start over a few times. Sometimes it adds things to list when I ask it to sometimes it adds to to global or to each account. I could make each account their own treasury folder since I use plugin manager anyway was just wondering if anyone knows what I'm talking about or wants to fix it before I go that route. Thanks in advance.

**Comment by RubenatorX** [comment]
You cannot use `send` to do treasury commands to add/remove items from lists because due to limitations in the way the settings/config library works that manages the settings file, if you use `send` addon to try and have them all add it at once all the instances end up writing to the settings file at the same time, resulting in them clobbering the file. If you don't use `send` to do this, you should not have this problem.

**Comment by OverloadingTrucks** [comment]
Ah yes that is how I have been doing it. Will start from scratch again and see how it goes. Thank you!
