### ISSUE TITLE
Yush: "No matching file found" error

### ISSUE THREAD

**Issue by Subadai** [Windower/Lua#1934]
Yush gives an error on load for my character Subadai: "No matching file found for Subadai (PLD/BLU)", even though I have placed a lua file in the data folder (mine is C:\Windower4\addons\Yush\data\). I have tried naming the file Subadai_PLD_BLU.lua, Subadai_PLD.lua, Subadai.lua, and binds.lua as per the readme. File extensions are visible so it's not accidentally named binds.lua.txt.

**Comment by RubenatorX** [comment]
Make sure that you don't secretly have more than one set of windower files and you're modifying the files in a different one than you are actually running.
Aside from that, you may have to come chat with us in discord https://discord.gg/v6pk6uy
because I tested it by making it think my name was Subadai and it worked just fine:
![yush](https://user-images.githubusercontent.com/5944121/92503618-c4705d80-f1be-11ea-8802-3f2fbb429d41.png)
![yush2](https://user-images.githubusercontent.com/5944121/92503623-c6d2b780-f1be-11ea-834a-a11126ba1527.png)

**Comment by RubenatorX** [comment]
The file contained syntax errors and Yush doesn't report those back and just acts like its a bad/missing file.

**Comment by Subadai** [comment]
Thanks for helping!
