### ISSUE TITLE
config.load not working as intended (i think)

### ISSUE THREAD

**Issue by giulianoriccio** [Windower/Lua#197]
the config lib is not merging the settings coming from the xml correctly.
i noticed this because a ls mate told me that my plugin wouldn't load the settings he changed in the xml, but then he said the same thing for the position of another plugin (scoreboard if i'm not wrong).
test below

``` xml
<?xml version="1.1" ?>
<settings>
    <global>
        <a>4</a>
        <b>5</b>
        <c>6</c>
    </global>
</settings>
```

``` lua
config = require('config')

-- test 1

defaults = T{['a'] = 1, ['b'] = 2, ['c'] = 3}

settings = config.load(defaults)
write(defaults.a..' '..defaults.b..' '..defaults.c)
write(settings.a..' '..settings.b..' '..settings.c)

--[[
    output:
        1 2 3
        1 2 3
    expected:
        1 2 3
        4 5 6
]]

-- test 2

defaults = T{['a'] = 1, ['b'] = 2, ['c'] = 3}

settings = config.load(defaults, true)
write(defaults.a..' '..defaults.b..' '..defaults.c)
write(settings.a..' '..settings.b..' '..settings.c)

--[[
    output:
        4 5 6
        4 5 6
    expected:
        4 5 6
        4 5 6
]]
```

**Comment by z16** [comment]
It was a bug I introduced with an earlier update today. It's fixed now, try restarting the launcher (or manually downloading the new tablehelper.lua).

**Comment by giulianoriccio** [comment]
now it overwrites with or without the 2nd parameter set to true
moreover i noticed these 2 lines where the bracket should be moved before the comparison operator:

tablehelper.lua 236: `elseif type(oldval == 'boolean') then`
tablehelper.lua 244: `elseif type(oldval == 'string') then`

edit:
i've changed locally this line config.lua 105: `return confdict:merge(parsed['global']:update(parsed[get_player()['name']:lower()], true))`
to config.lua 105: `return confdict:copy():merge(parsed['global']:update(parsed[get_player()['name']:lower()], true))`
and looks like it works as expected in the test i've made

will fix them and make a pull request if it's ok with you

**Comment by z16** [comment]
Sure, I merged it, thanks for the fix.

**Comment by giulianoriccio** [comment]
i'm not using that option, but your last change won't make it overwrite the original table when the 2nd parameter is set to true since it will copy it regardless.

**Comment by z16** [comment]
That is intended. The parameter name may be misleading, but it's not supposed to actually overwrite that table, only overwrite default values if there's a type mismatch, instead of throwing a hissy fit spamming the chatlog with errors. That's why, when overwrite is set to true it uses `confdict:update()` instead of `confdict:merge()`, which blindly overwrites values in the original table, while `table.merge` tries to take type safety into account.

For example, if the original table expected a table, but gets a string, `table.merge` will try to split the string by commata and return the resulting table. That's why `<somelist>a,b,c</somelist>` would assign `settings.somelist = {a, b, c}`, whereas `table.update` would assign `settings.somelist = 'a,b,c'`. This was done to facilitate array assignment, instead of having to do `<item>a</item><item>b</item><item>c</item>`. It tries similar conversions for some other values.

It will still return a new table, so the original default table remains intact, in case people need the default values at runtime, for whatever reason.

**Comment by giulianoriccio** [comment]
ok, i got it.
thank you for the explanation.
