### ISSUE TITLE
Treasury

### ISSUE THREAD

**Issue by gimlic1** [Windower/Lua#2037]
Treasury isn't saving correctly into the settings.xml
Any time I add or remove items from the lists it makes those changes to Global instead of the character making the changes.
Didn't seem to be an issue before I started multi-boxing.

**Comment by joshk6656** [comment]
It's a known issue when mulitboxing. Each config file is loaded into
memory, and when u change it I believe it overwrites the others when it
saves.

Best way is to unload on all but the one you are adjusting, make changes,
then reload on all.

It probably should be converted to a file per character instead of a file
that holds them all.
