### ISSUE TITLE
Strange Lua syntax in addons/libs/resources.lua

### ISSUE THREAD

**Issue by ghost** [Windower/Lua#2239]
https://github.com/Windower/Lua/blob/ae2a26c6fab2756328717db856d27337648c5f70/addons/libs/resources.lua#L53

How does that work without parenthesis around the function? And does the outer function even have a purpose?

**Comment by Nifim** [comment]
In correct place to ask questions about the code please come to the discord to ask such questions

**Comment by ghost** [comment]
I'd expect the correct place to discuss source code would be the place where it is developed and hosted, no? Anyway, is this a modified Lua 5.1 runtime being used, or just some odd quirk of how the Lua library is arranged?

**Comment by RubenatorX** [comment]
The issue tracker is for tracking issues, not for satisfying your curiosity about Lua. If you have development questions, use the #development channel in the Windower discord.

**Comment by z16** [comment]
Our junior devs are confused sometimes, please excuse their rudeness. While you are more likely to get an answer on our Discord server (and faster, too), this is not the wrong place to ask about potential issues with the code.

Anyway, this is answered in the last paragraph of [this section of our documentation](https://github.com/Windower/Lua/wiki/Windower-Lua-API#lua), and in more details in [this section](https://github.com/Windower/Lua/wiki/Windower-Lua-API#grammar). We use a modified Lua 5.1, and one modification is to the Lua grammar, so that literals can be called and indexed directly. For the same reason, this would work as well (if you `require` our `maths` library):
```lua
print(2.5:floor())
```
