### ISSUE TITLE
Skewed textbox?

### ISSUE THREAD

**Issue by ghost** [Windower/Lua#365]
I've had a problem for a little while that sometimes, part of addons are covered up. As if perhaps a textbox's size is distorted? Restarting Windower is the only way to fix it that I know of.

I've tried //unloadall and //lua unloadall and while everything is unloaded, this...square doesn't disappear.

It can cover different addons. Sometimes it interferes with my own addon gametime. I had the issue before writing that addon too.

It's not a major thing.. but if an answer is known, I'd love to know

It might be relevant that I'm running an NVIDIA 560 Ti. The game itself is not interfered with, only addon/plugin display. I've also never seen the problem affect addons in the lower half of my display, but all that I run in that area is Timers, Tparty and Attainment.

I have no way to immediately reproduce this...it just does it sometimes when I do something with an addon (any of several addons).

![oversided_textbox](https://f.cloud.github.com/assets/4692766/714347/bb879d9c-defb-11e2-9340-35e9187719d3.png)

**Comment by z16** [comment]
Any chance you mean [this](https://github.com/Windower/Issues/issues/41)? Windower errors should go to [here](https://github.com/Windower/Issues), this repository is specifically for Lua/LuaCore issues.

Although I'll let you know that in the new Hook currently in development this has been fixed (the text renderer has been rewritten entirely). It's not ready for release yet, because we will change quite a few other things alongside it, but just to let you know it's been taken care of and should be made public in the near future.

**Comment by ghost** [comment]
Thanks!
