### ISSUE TITLE
odd behaviour

### ISSUE THREAD

**Issue by sebyg666** [Windower/Lua#550]
I'm getting odd behaviour in game from addons since a major windower update a couple days ago. highlight broke, makes player names appear with a list of numbers before the name, sandbox is possibly causing double text issues when 2 boxin, im getting several lines in log been doubled on both screens, the Delve addon that normally shows all delve stuff is also not working for me. im guessing something changed in the core. i know u guys are understaffed and such. just wanted to point them out, your probably all aware of these already id imagine. thanks

**Comment by z16** [comment]
Please make separate issues for any items you find. Also note that we don't do addons at all, those are maintained by whoever created them. You should try to post on their bugtracker about them.

The duplication is not a plugin bug, it's because the game receives duplicate packets, and you're probably using Battlemod, which works based on incoming packets.
