### ISSUE TITLE
skills table returned by windower.ffxi.get_player()

### ISSUE THREAD

**Issue by mujihina** [Windower/Lua#796]
Hi there,
  Currently (4.1-dev), the indexes of the table are strings (shouldn't they be numbers, and consistent with the skills.lua table under /res?), but that's something to talk about some other day. 

Could you please address these minor issues with the current table?
1) blue_magic has '_magic' in it, but all the others magic skills do not).  Either add  '_magic' to all, or take '_magic' out of blue_magic.
2) ninjitsu: the game and other places use 'ninjutsu'

**Comment by alphaONE2** [comment]
It's listed as Blue Magic in the skills window, the others are just listed as Enhancing or Enfeebling, there's no problem here; "ninjitsu" is definitely a typo though.

**Comment by z16** [comment]
Fixed ninjutsu, I'll see about adjusting the rest, but I need to make sure no addons break because of it first.

**Comment by z16** [comment]
As for the naming part, ideally all names should be the same. The full skill names are the names as displayed in the chat log on skill up, which includes the "magic" part. Since we use those skill names for everything else, it would be good if the `skills` table returned by `windower.ffxi.get_player` would also use those names, if there are no conflicts with other addons.

**Comment by z16** [comment]
Adjusted it and the relevant addons.
