### ISSUE TITLE
Gearswap - work in a multi-language

### ISSUE THREAD

**Issue by tainai-kaiki** [Windower/Lua#835]
hello.

I'am Japanese.
Although I had used the Spellcast regularly, I hear that support goes out and it considers shift to a Gearswap.
But gearswap was not work in my environment.

I would like to include the following functions in Gearswap.
1. Language is judged automatically.
2. Use the name corresponding to the language for equipment and spells.

plz help me X(

**Comment by Byrth** [comment]
Hello tainai-kaiki!

GearSwap is actually designed to be NA and JP, but we needed to translate some resource files before I could enable it. I will check which we still need translated tonight.

**Comment by Byrth** [comment]
It seems that we need to translate four more resources. Many of the values that were still in english in Spellcast will still be in english in GearSwap (like spell type), but spell names and elements and so on will be translated as appropriate.

It makes sense to do all of the translation possible before releasing a JP-compatible version, because it will probably never be completely translated and I do not want to disturb users later by translating more.

Perhaps I can have a version out in less than two weeks.

**Comment by tainai-kaiki** [comment]
Hello Bing :D

Thank you for the response and investigation.

I have understood that these problems had to be solved gradually.

We would like to wait for upgrade in a distant island country.
If required, we 120 million japanese will raise and debug full force ^^b

**Comment by tainai-kaiki** [comment]
oh.. sorry Bing > Bryth X(

**Comment by Byrth** [comment]
Heh =p

I have started making changes to GearSwap so this is possible. It looks like I need a function exposed (in LuaCore) that will convert from shift-JIS to Unicode. After that, I can test some more.

**Comment by tainai-kaiki** [comment]
Hello Byrth.  (Furthermore, I am sorry by mistake...)

> I have started making changes to GearSwap so this is possible.
> Awesame!!
> I appreciate that your action is early^^

**Comment by Byrth** [comment]
Hello tainai-kaiki! No problem about the name!

I have a question about target shortcuts on the JP client. Are they still `<t>`, `<me>`, and so forth, or are they something else?

**Comment by Byrth** [comment]
Okay, I just pushed a version live. It does not automatically detect the client's region (Japanese, English, etc.) because I wanted to give everyone the option to play in whatever language they want. There are a handful of variables that will not work until we push a new set of resources live, but by and large it should work.

There is no Japanese documentation (I'm sorry! I don't speak Japanese.)

In order to enable japanese language options, use this in the get_sets() function:

> set_language('japanese')

**Comment by tainai-kaiki** [comment]
Hello. 

> <t>, <me>

They are the same also at Japanese environment.

**Comment by tainai-kaiki** [comment]
> t, me

**Comment by tainai-kaiki** [comment]
> Okay, I just pushed a version live.

It is a prompt action! It was surprised!
I try on this.
Thank you byrth ^^

> There is no Japanese documentation 
> (I'm sorry! I don't speak Japanese.)

Ok!! No problem.
Because Japanese nice guys surely translates by Japanese wiki :D

**Comment by Byrth** [comment]
Haha, yay! Let me know if anything goes wrong. I will respond faster if you post to my issue tracker here:
https://github.com/Byrth/Lua/issues?direction=desc&sort=created&state=open

**Comment by tainai-kaiki** [comment]
I see ^^
If something is, I will post there.
Thank you!!
