### ISSUE TITLE
[Bug] Gearswap not swapping one item in a single slot, at random times

### ISSUE THREAD

**Issue by Sechs** [Windower/Lua#983]
Someone might be familiar with an issue I used to have in the past on Gearswap.
Randomly it won't swap in precast gear for my Nightingale/Troubadour JAs, with the result that one of them will end up 15 seconds before the other.
Byrth "cleaned up code" some time ago and never saw this happening (or at least I didn't notice).
Since the last patch this issue is back.
So far I've only seen it happen for Troubadour, it seems Nightingale always gets it right.

_Macro being used_
/ja Nightingale <me>
/wait 1
/ja Troubadour <me>

_Screenshot example of Troubadour wearing off earlier_
http://s30.postimg.org/oo8z730pt/troub_error.png
Troubadour didn't get the correct +15 seconds duration from Bard's Justaucorps +1.

_Screnshot example of JAs getting the buff correctly_
http://s11.postimg.org/mr6p4fehf/troub_ok.png
After this Troubadour lasts the correct amount of time and wears off 1 second after Nightingale

_Inside my Gearswap file I use the following lines for precast_
    sets.precast['Nightingale'] = {feet="Bihu Slippers +1"}
    sets.precast['Troubadour'] = {body="Bihu Justaucorps +1"}
As you can see I use the full name and not the shortened one.
I remember Troubadour being spelled wrong somewhere (augment on Body? Wiki?) but I can't find the wrong one again. Resources have the right one.

I'm not linking my BRD lua because I doubt that's the issue.
In the same exact circumstances one time it works perfectly, the time after it doesn't. Can't be a lua thing imho.

**Comment by joshk6656** [comment]
I've had this issue a lot when I have spellcast loaded at the same time. You don't right?

Just trying to eliminate one possibility.

**Comment by Sechs** [comment]
Haven't loaded up Spellcast in months.
Thanks for the tip though ;)

**Comment by joshk6656** [comment]
You cropped the part of them wearing off, although I'm sure everyone believes you :)

It prints the equip changes correctly, but doesn't actually equip / grant you the bonus?

**Comment by Sechs** [comment]
Lol well yes, I thought that was less relevant, there's not much to be seen there.
I don't know what happens. Either the JA gets executed before the body is _really_ equipped or, more likely, it gets executed when Gearswap is already in its "aftercast" phase.

Another Hypothesys is that for some reason there's an "error" and Gearswap TRIES to equip that item (body) but it doesn't succeed, as if the item wasn't in my inventory, or as if the name in the Lua precast set was wrong.

The bizarre part in all of this is that this is not something that happens 100% of the time... it's random. Majority of the times I'm fine I think.

**Comment by Sechs** [comment]
Anybody else got a clue what could be going on?
Tips? Ideas for tests that I can perform to nail the issue?

**Comment by Byrth** [comment]
Can you check if this still happens on the -dev hook you're using for Timers? There were some changes to the deduplication packets recently that might have fixed it.

**Comment by Sechs** [comment]
I was currently using an external macro with  /raw to circumvein the issue, but I can revert to the normal one to see, I'll do it tonight actually since I plan to keep farming CP on BRD.
Is there any specific option I can turn on to help you in case the thing happens again? Some logging tool, dunno, anything you can think of that would help you.

**Comment by Sechs** [comment]
Over 20 uses of Nitro and it didn't happen, for now.
Small numbers maybe, but leaning to think the issue is likely gone?
What could have caused it before though, and why was it happening only to a bunch of people and not to many others like you?

**Comment by Sechs** [comment]
I was too hasty, happened once today in Outer Ra'kaznar =/
And again in Port Bastok (after everything was 100% loaded up in memory) and some more times as well.

**Comment by Byrth** [comment]
Hmm.... were you using the -dev hook for sure? Arcon says the required changes were not in the live hook. The -dev one should be pushed live soon.

The problem might have been in hook deduplication code. For a few packet IDs, including one that manipulates inventory, Hook was blocking any chunks with the same contents as another chunk with the same ID that had been seen in the last 4 incoming UDP packets. Because you might, for instance, swap body late in your change to aftercast gear and then use Troubadour (which would put Body on), it's possible that it was blocking the second change even though there was an intermediate change that swapped you back to your idle body (or whatever).

So, for instance, it could have been doing:
Gendewitha Bliaut +1 (Idle) -> Bihu Justaucorps +1 (Mordant Rime, idk) -> Gendewitha Bliaut +1 (Idle - Blocked by hook because you already received an incoming Gendewitha Bliaut +1 packet really recently) -> Bihu Justaucorps +1
Because Hook blocks the Gendewitha Bliaut +1 packet, when you go to use Troubadour GearSwap believes that you are currently wearing Bihu Justaucorps +1 and does not send an outgoing equip packet.

However, after writing this up and looking at your pictures again I actually believe this may not be your problem. I think the real problem is:
Night precast -> Troub Precast -> Night Aftercast
The error picture looks like Nightingale's aftercast equip commands and Troub's precast could have been in the same outgoing packet, in which case Nightingale's aftercast would have overwritten Troub's precast. Because JA effects are actually calculated at some point after when the JA packet arrives, the final body equip assignment in the outgoing packet that contains the JA command is going to determine which body is worn when the JA actually goes off.

I'll try to think of some way around this, but the solution may end up being me trying once again to improve the midcast() function.

**Comment by Sechs** [comment]
Hook was 4.2.7.3.
I performed another test. Went to Rabao, used JAs, checked how long they lasted, then swapped sj to reset timers, rinse and repeat.
With so many tries over a short time I saw the error happen again consistently altough still randomly.

When I'm /NIN or /DNC I idle in Bihu Justaucorps +1.
When I'm any other subjob (normally /WHM, /BLM or /RDM) I idle in Heka's Kalasiris.
This issue happens in all possible situations. Wether I'm in the middle of very conceited situations where I'm spamming JAs/Songs, and even in situations where everything is pretty calm, for instance the last testing scenario had me completely idle in a town (Rabao) simply using my NiTro macro.
Calm situations are more common tbf, and the error still happens, randomly.

The idea you had about Night's aftercast mixing up packets with Troub's precast may very well be the cause. Altough I still don't get why this doesn't happen all of the times... maybe lag, or something?
Do you want me to keep testing? Otherwise I'll momentarily swap back to my /raw macro.

My real concern about this "error" is not just this single circumstance, which I can easily circumvein using the /raw macro "trick". My real concern is that this error might happen, randomly, in several other situations of many other of my jobs, and I just never noticed so far =/ This is why I've been so vocal about it.
But in the end I don't really want to stress you guys too much, sorry if I sounded too bitchy/demanding.

**Comment by Byrth** [comment]
The first problem I outlined is easy to fix, but it is in hook and Arcon is on vacation.

The second problem is harder and will need to be fixed in two parts:
1) I need to make midaction() perfect somehow.
2) You need to use midaction() to cancel your aftercast equipment commands.

**Comment by Sechs** [comment]
Does this imply the "problem" could also be solved by me not using Aftercast() after those 2 JAs?
I could rethink my Luas, tbf I don't really need an aftercast for many JAs, Night/Troub being a good example.

Meanwhile I'll look for more information on how to implement midaction() for JAs in my luas.

**Comment by Byrth** [comment]
You would want to use something like:

if midaction() then return end

In your aftercsst section.

**Comment by Byrth** [comment]
I'm going to close this and open an issue in /Issues and on my own tracker for the two fixes. In the meantime, you can try adding the midcast aftercast line.

For the record, This would affect anything where you can start the next action before the previous action's message has shown up in your chat log. It's also not really a bug, in that it was an acknowledged consequence of dropping my forced midaction delay.

If you put:
`if midaction() then return end`
at the top of your aftercast section, it should handle everything (as well as midaction() works at the moment).

**Comment by Byrth** [comment]
Also, ftr, this is only going to be an issue for things that follow JA uses. So Nightingale -> (Troubadour) or Sneak Attack -> (Weapon Skill). Forced delay prevents it from becoming an issue for things that follow weapon skills, magic, etc. because no action can successfully resolve quickly enough for it to be an issue.
